const PHOTOS = [
  { src: "images/wedding-01.jpg", caption: "" },
  { src: "images/wedding-02.jpg", caption: "" },
  { src: "images/wedding-03.jpg", caption: "" },
  { src: "images/wedding-04.jpg", caption: "" },
  { src: "images/wedding-05.jpg", caption: "" },
  { src: "images/wedding-06.jpg", caption: "" },
  { src: "images/wedding-07.jpg", caption: "" },
  { src: "images/wedding-08.jpg", caption: "" },
  { src: "images/wedding-09.jpg", caption: "" },
  { src: "images/wedding-10.jpg", caption: "" },
  { src: "images/wedding-11.jpg", caption: "" },
  { src: "images/wedding-12.jpg", caption: "" },
  { src: "images/wedding-13.jpg", caption: "" },
  { src: "images/wedding-14.jpg", caption: "" },
];
